import type { NextPage } from 'next'
import {useState} from 'react'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  // const values = useState('')
  // const inputText = values[0];
  // const setInputText = values[1];
  const [inputText,setInputText] = useState('');
  const [history, setHistory] = useState([]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          React Hooks!
        </h1>
         <input 
          type= 'text'
          placeholder='enter text here'
          onChange={(e) => {
            setInputText(e.target.value);
            setHistory([...history, e.target.value])
          }}
        />
       <div>
         {inputText}
       </div>
        <div>
          <ul>
            {history.map((item) => {
              return <div>{item}</div>
            })}
          </ul>
        </div>
      </main>
    </div>
  )
}

export default Home